// 220 nationality demonyms covering all ISO 3166-1 countries + common dependencies.
// Used by the User Registration form. Sorted alphabetically so the <datalist>
// suggests in order. If you add an entry, keep the list sorted and unique.
export const NATIONALITIES: readonly string[] = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "American Samoan",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Antiguan",
  "Argentinian",
  "Armenian",
  "Aruban",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Botswanan",
  "Brazilian",
  "British",
  "British Virgin Islander",
  "Bruneian",
  "Bulgarian",
  "Burkinabé",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Caymanian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Christmas Islander",
  "Cocos Islander",
  "Colombian",
  "Comoran",
  "Congolese",
  "Cook Islander",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Curaçaoan",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dominican (Republic)",
  "Dutch",
  "East Timorese",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Eswatini",
  "Ethiopian",
  "Falkland Islander",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "French Guianese",
  "French Polynesian",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Greenlandic",
  "Grenadian",
  "Guadeloupean",
  "Guamanian",
  "Guatemalan",
  "Guernsey",
  "Guinean",
  "Guinea-Bissauan",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "I-Kiribati",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jersey",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Korean (North)",
  "Korean (South)",
  "Kosovar",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourgish",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Manx",
  "Marshallese",
  "Martinican",
  "Mauritanian",
  "Mauritian",
  "Mayotte",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monégasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Caledonian",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niuean",
  "Norfolk Islander",
  "Northern Mariana Islander",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Pitcairn Islander",
  "Polish",
  "Portuguese",
  "Puerto Rican",
  "Qatari",
  "Réunionese",
  "Romanian",
  "Russian",
  "Rwandan",
  "Sahrawi",
  "Saint Helenian",
  "Saint Kittian",
  "Saint Lucian",
  "Saint Pierre and Miquelon",
  "Saint Vincentian",
  "Salvadoran",
  "Sammarinese",
  "Samoan",
  "São Toméan",
  "Saudi",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Sint Maartener",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tokelauan",
  "Tongan",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vatican",
  "Venezuelan",
  "Vietnamese",
  "Wallisian",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];
